export default [
  {
    link: 'http://www.ladbible.com',
    dates: 'Jul 2018 - present',
    companyName: 'LADbible Group',
    icon: 'work',
    jobTitle: 'Software Engineer',
    jobDesc: 'Rebuilding all company websites, learning deployment technologies, writing for company Medium publication.',
    skills: 'React, HTML, CSS, GraphQL, Koa, Docker, Kubernetes, CircleCI, Jenkins, BrowserStack',
  },
  {
    link: 'https://www.northcoders.com',
    dates: 'May - Jun 2018',
    companyName: 'Northcoders',
    icon: 'work',
    jobTitle: 'Tutor (Saturdays)',
    jobDesc: 'Supporting Northcoders students on the part-time course with front end development.',
    skills: 'React, Redux, Redux-Thunk, Webpack, HTML, CSS',
  },
  {
    link: 'https://www.careicon.com',
    dates: 'Aug 2017 - Jul 2018',
    companyName: 'Careicon',
    icon: 'work',
    jobTitle: 'Front End Developer',
    jobDesc: 'Currently under NDA.',
    skills: 'React, Redux, Redux-Saga, Storybook, Webpack, Jest, Git, HTML, CSS',
  },
  {
    link: 'https://www.northcoders.com',
    dates: 'May - Aug 2017',
    companyName: 'Northcoders',
    icon: 'study',
    jobTitle: 'Developer Bootcamp',
    jobDesc: '12 weeks of intensive training in JavaScript and programming skills.',
    skills: 'JavaScript, Node.js, Express, MongoDB, SQL, React, Redux, Redux-Thunk, Webpack',
  },
  {
    link: 'https://www.codecademy.com',
    dates: 'Jan - May 2017',
    companyName: 'Codecademy',
    icon: 'study',
    jobTitle: 'Beginner Developer',
    jobDesc: 'Self-directed study in preparation for Northcoders bootcamp.',
    skills: 'JavaScript, Git, JQuery, Sass',
    hideIfNotHunting: true,
  },
  {
    link: 'https://freecodecamp.com',
    dates: 'Jan - May 2017',
    companyName: 'FreeCodeCamp',
    icon: 'study',
    jobTitle: 'Beginner Developer',
    jobDesc: 'Self-directed study in preparation for Northcoders bootcamp.',
    skills: 'Basic JavaScript, Object Oriented and Functional Programming, Basic Algorithm Scripting',
    hideIfNotHunting: true,
  },
];
